[package]
name = "interruptible_polling"
description = "General purpose polling tasks with RAII-driven fast clean exits"
version = "0.1.0"
edition = "2021"
authors = ["Chris Henk"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/LittleBoxOfSunshine/interruptible-polling"
readme = "README.md"
keywords = ["poll", "polling", "task"]
