[package]
name = "interruptible_polling"
description = "General purpose polling tasks with RAII-driven fast clean exits"
version = "0.0.1"
edition = "2021"
authors = ["Chris Henk <Chris.Henk@unobtainium.software>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/LittleBoxOfSunshine/interruptible-polling"
readme = "README.md"
keywords = ["poll", "polling", "task"]

[dev-dependencies]
tokio = { version = "1.29.1", features = ["sync", "macros", "rt"] }
serde_json = "1.0.103"
